version: 2

models:
  - name: dim_customers
    description: "Dimension table of customers with basic profile data."
    columns:
      - name: customer_id
        description: "Unique ID for each customer."
        tests:
          - unique
          - not_null

  - name: fact_orders
    description: "Fact table of customer orders with amounts and dates."
    columns:
      - name: order_id
        description: "Unique ID for each order."
        tests:
          - unique
          - not_null
